### ISSUE TITLE
The GNO is correctly withdrawn, but it isn't shown in the interface

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/dx-mgn-pool-react#13]
Description
The GNO is correctly withdrawn, but it isn't shown in the interface.

Pre-conditions:

Had an existent GNO deposit on the interface in metamask.
Being on the MGN unlocked period.
Steps to reproduce:

Go to https://dx-mgn-pool.staging.gnosisdev.com/
Tap on the Withdraw button.
Confirm the transaction with metamask.
Observe.
Expected behaviour:
The transaction is correctly made and it's shown in the balance on the interface.

Actual behaviour:
The transaction is correctly withdrawn (we can see it on Etherscan) but the interface doesn't show the new balance, and still shows the withdraw button.

Environment
Chrome version: 73.0.3683.86
App Version: 0.0.1-RC16
Contracts version: ^0.1.3-RC4
Metamask - Rinkeby

Screenshots:
https://drive.google.com/open?id=1Dv9G7deZhr2tNEboqdpaaWg05dWTSVoL
https://drive.google.com/open?id=1vgCWHXrQMRmk5dkN_C-X-mS_Hzrp7cml
https://drive.google.com/open?id=1KF_AZekMCHaYpJWSxTKuXve5nGcSiJkp

**Comment by W3stside** [comment]
@MicaelaPesado Is this still an issue?

**Comment by MicaelaPesado** [comment]
No, it works fine in the latest version, now I'll close it.
