### ISSUE TITLE
Safe iOS won’t notify the user to confirm deposit with the app

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/dx-mgn-pool-react#14]
Describe the bug
When submitting the deposit, after confirming the transaction with the browser extension, there's no second confirmation requested by the app

Pre-conditions:

Having the Gnosis Safe browser extension (rinkeby) connected in the computer with a Safe synchronised.
To Reproduce

Go to https://dx-mgn-pool.staging.gnosisdev.com/
Make a deposit in any pooling
Confirm with extension
Check Cellphone App for second confirmation
Observe
Expected behavior
The notification is correctly recived and the user can confirm or reject the transaction.

Actual behavior
The notification is not recived in the app, and the browser extension keeps waiting the confirmation.

Smartphone:

Device: iPhone X
iOS Version: iOS 12.1
Safe version: 1.1.0

Chrome version: 73.0.3683.86
App Version: 0.0.1-RC16
Contracts version: ^0.1.3-RC4

**Comment by W3stside** [comment]
@MicaelaPesado please try going into the Chrome Extension and clicking on `Resync with mobile app`

Try again after this - it worked for me. Closing for now - please re-open if no fix.

**Comment by MicaelaPesado** [comment]
We can't re- test it because there isn't any pool running actually. Anyway, we didn't re-sync from the mobile app, becuse we think that the notification could be sent automatically, either if it's resynced, or not. I'll keep it closed, and we will re test it then.
