### ISSUE TITLE
Error estimating gas in mainnet

### ISSUE THREAD

**Issue by anxolin** [gnosis/dx-mgn-pool-react#25]
It's using 5Gwei. Safe low is right now 11Gwei and avf is 16Gwei.

If metamask underestimate, we may use: https://safe-relay.gnosis.pm/api/v1/gas-station/

**Comment by W3stside** [comment]
fixed in commit `4111dcfdf98f18bc9f3192c2733255e070912f6e`

**Comment by anxolin** [comment]
It should use the Safe relay for closing. That commit only increase the gas price: https://github.com/gnosis/dx-mgn-pool-react/commit/4111dcfdf98f18bc9f3192c2733255e070912f6e
